### ISSUE TITLE
[BUG] Termux, fastfetch sudenly stop/crash.

### ISSUE THREAD

**Issue by Dan1jel** [fastfetch-cli/fastfetch#704]
# General description of bug:

* What happened: Command stops, same config works on Raspberry Pi (v.2.2.3-7).
* What should happen: Should complete, assume it something with Termux todo, not fastfetch itself but dont know what. 
* Did it work in an older version: Yes, all before, first time seeing this. 
* Where did you get the binary:  Installed with a package manager (Termux).

# Often helpful information:

Screenshot:
![signal-2024-01-29-150808_002](https://github.com/fastfetch-cli/fastfetch/assets/4266424/f2e31ba9-79e3-44b2-b485-126ad01b0a61)

The content of the configuration file you use (if any):
```
tested with my config or fastfetch config, same thing "Segmentation fault"
```

Output of `fastfetch -c ci.jsonc --format json`:

```
~ $ fastfetch -c ci.jsonc --format json
Segmentation fault      
```

Output of `fastfetch --list-features`:
```
~ $ fastfetch --list-features
threads
vulkan
freetype
```

## If fastfatch crashed

Paste the stacktrace here. You may get it with:

```
~ $ type fastfetch
fastfetch is hashed (/data/data/com.termux/files/usr/bin/fastfetch)
 ~ $ gdb /data/data/com.termux/files/usr/bin/fastfetch
GNU gdb (GDB) 14.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-android".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.                       
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /data/data/com.termux/files/usr/bin/fastfetch...
(No debugging symbols found in /data/data/com.termux/files/usr/bin/fastfetch)
(gdb) run
Starting program: /data/data/com.termux/files/usr/bin/fastfetch
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/data/data/com.termux/files/usr/lib/libthread_db.so".
warning: section .note.gnu.build-id not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libdl.so
warning: section .dynsym not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libdl.so
warning: section .gnu.version not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libdl.so
warning: section .gnu.version_d not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libdl.so
warning: section .gnu.hash not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libdl.so
warning: section .dynstr not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libdl.so
warning: section .rela.plt not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libdl.so
warning: section .eh_frame_hdr not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libdl.so
warning: section .eh_frame not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libdl.so
warning: section .plt not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libdl.so
warning: section .dynamic not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libdl.so
warning: section .got.plt not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libdl.so
warning: section .bss not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libdl.so
warning: section .note.android.ident not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .note.gnu.build-id not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .dynsym not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .gnu.version not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .gnu.version_r not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .gnu.hash not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .dynstr not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .rela.dyn not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .relr.dyn not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .rela.plt not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .rodata not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .eh_frame_hdr not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .eh_frame not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .plt not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .data.rel.ro not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .fini_array not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .dynamic not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .got not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .got.plt not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .data not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .bss not found in .gnu_debugdata for /system/lib64/libnetd_client.so
warning: section .note.android.ident not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .note.gnu.build-id not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .dynsym not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .gnu.version not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .gnu.version_r not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .gnu.hash not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .dynstr not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .rela.dyn not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .relr.dyn not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .rela.plt not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .rodata not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .gcc_except_table not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .eh_frame_hdr not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .eh_frame not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .plt not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .data.rel.ro not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .fini_array not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .init_array not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .dynamic not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .got not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .got.plt not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .data not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .bss not found in .gnu_debugdata for /system/lib64/libc++.so
warning: section .note.android.ident not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .note.gnu.build-id not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .dynsym not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .gnu.version not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .gnu.version_d not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .gnu.version_r not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .gnu.hash not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .dynstr not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .rela.dyn not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .relr.dyn not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .rela.plt not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .rodata not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .eh_frame_hdr not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .eh_frame not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .plt not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .data.rel.ro not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .fini_array not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .dynamic not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .got not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .got.plt not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .data not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so
warning: section .bss not found in .gnu_debugdata for /apex/com.android.runtime/lib64/bionic/libm.so

         -o          o-           ┌──────────────────────────────────────┐
          +hydNNNNdyh+                Android REL 14 aarch64
        +mMMMMMMMMMMMMm+            󰐿  Google Pixel 8 Pro
      `dMMm:NMMMMMMN:mMMd`            5.15.110-android14-11-gcc48824eebe8-6
      hMMMMMMMMMMMMMMMMMMh            Tensor G3 (9) @ 1.70 GHz
warning: section .note.android.ident not found in .gnu_debugdata for /systeo
warning: section .note.gnu.build-id not found in .gnu_debugdata for /systemo
warning: section .dynsym not found in .gnu_debugdata for /system/lib64/libvo
warning: section .gnu.version not found in .gnu_debugdata for /system/lib64o
warning: section .gnu.version_r not found in .gnu_debugdata for /system/libo

………
Continues several lines with “warning:…”
………

warning: section .bss not found in .gnu_debugdata for /apex/com.android.vndo
                                      Mali-G715 [Integrated]
                                      8.30 GiB / 11.32 GiB (73%)
                                      236 (dpkg)
[Detaching after fork from child process 15940]
                                      bash 5.2.15
[Detaching after fork from child process 15941]

Program received signal SIGSEGV, Segmentation fault.
0x0000007ff288bd30 in long long StrToI<long long, -9223372036854775808ll, 9)
   from /apex/com.android.runtime/lib64/bionic/libc.so
(gdb) bt
#0  0x0000007ff288bd30 in long long StrToI<long long, -9223372036854775808l)
   from /apex/com.android.runtime/lib64/bionic/libc.so
#1  0x00000055556293c8 in ?? ()
#2  0x000000555562916c in ?? ()
#3  0x0000005555605f94 in ?? ()
#4  0x00000055555ccab8 in ?? ()
#5  0x00000055556579d8 in ?? ()
#6  0x0000007ff28726ec in __libc_init ()
   from /apex/com.android.runtime/lib64/bionic/libc.so
(gdb)

```

**Comment by CarterLi** [comment]
> #1  0x00000055556293c8 in ?? ()
#2  0x000000555562916c in ?? ()
#3  0x0000005555605f94 in ?? ()
#4  0x00000055555ccab8 in ?? ()
#5  0x00000055556579d8 in ?? ()

It seems that the binary compiled by termux doesn't include debug symbols. Can you please compile it in source and try again?

**Comment by Dan1jel** [comment]
> > #1  0x00000055556293c8 in ?? ()
> #2  0x000000555562916c in ?? ()
> #3  0x0000005555605f94 in ?? ()
> #4  0x00000055555ccab8 in ?? ()
> #5  0x00000055556579d8 in ?? ()
> 
> It seems that the binary compiled by termux doesn't include debug symbols. Can you please compile it from source and try again?
> 
> Or you may use this one: [fastfetch.gz](https://github.com/fastfetch-cli/fastfetch/files/14086212/fastfetch.gz)

When I try to compile using 
```
run.sh
```
I get this error message 
```
[ 18%] Building C object CMakeFiles/libfastfetch.dir/src/detection/terminaltheme/terminaltheme.c.o
[ 18%] Building C object CMakeFiles/libfastfetch.dir/src/detection/terminalfont/terminalfont.c.o
[ 19%] Building C object CMakeFiles/libfastfetch.dir/src/detection/terminalshell/terminalshell.c.o
[ 20%] Building C object CMakeFiles/libfastfetch.dir/src/detection/version/version.c.o
[ 20%] Building C object CMakeFiles/libfastfetch.dir/src/detection/vulkan/vulkan.c.o
[ 21%] Building C object CMakeFiles/libfastfetch.dir/src/detection/weather/weather.c.o
[ 21%] Building C object CMakeFiles/libfastfetch.dir/src/logo/builtin.c.o
/data/data/com.termux/files/home/fastfetch/src/detection/vulkan/vulkan.c:12:10: fatal error: 'vulkan/vulkan.h' file not found
   12 | #include <vulkan/vulkan.h>
      |          ^~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [CMakeFiles/libfastfetch.dir/build.make:524: CMakeFiles/libfastfetch.dir/src/detection/vulkan/vulkan.c.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:87: CMakeFiles/libfastfetch.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:120: CMakeFiles/fastfetch.dir/rule] Error 2
make: *** [Makefile:202: fastfetch] Error 2
```

**Comment by CarterLi** [comment]
> > > #1  0x00000055556293c8 in ?? ()
> > #2  0x000000555562916c in ?? ()
> > #3  0x0000005555605f94 in ?? ()
> > #4  0x00000055555ccab8 in ?? ()
> > #5  0x00000055556579d8 in ?? ()
> > 
> > It seems that the binary compiled by termux doesn't include debug symbols. Can you please compile it from source and try again?
> > 
> > Or you may use this one: [fastfetch.gz](https://github.com/fastfetch-cli/fastfetch/files/14086212/fastfetch.gz)
> 
> When I try to compile using 
> ```
> run.sh
> ```
> I get this error message 
> ```
> [ 18%] Building C object CMakeFiles/libfastfetch.dir/src/detection/terminaltheme/terminaltheme.c.o
> [ 18%] Building C object CMakeFiles/libfastfetch.dir/src/detection/terminalfont/terminalfont.c.o
> [ 19%] Building C object CMakeFiles/libfastfetch.dir/src/detection/terminalshell/terminalshell.c.o
> [ 20%] Building C object CMakeFiles/libfastfetch.dir/src/detection/version/version.c.o
> [ 20%] Building C object CMakeFiles/libfastfetch.dir/src/detection/vulkan/vulkan.c.o
> [ 21%] Building C object CMakeFiles/libfastfetch.dir/src/detection/weather/weather.c.o
> [ 21%] Building C object CMakeFiles/libfastfetch.dir/src/logo/builtin.c.o
> /data/data/com.termux/files/home/fastfetch/src/detection/vulkan/vulkan.c:12:10: fatal error: 'vulkan/vulkan.h' file not found
>    12 | #include <vulkan/vulkan.h>
>       |          ^~~~~~~~~~~~~~~~~
> 1 error generated.
> make[3]: *** [CMakeFiles/libfastfetch.dir/build.make:524: CMakeFiles/libfastfetch.dir/src/detection/vulkan/vulkan.c.o] Error 1
> make[3]: *** Waiting for unfinished jobs....
> make[2]: *** [CMakeFiles/Makefile2:87: CMakeFiles/libfastfetch.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:120: CMakeFiles/fastfetch.dir/rule] Error 2
> make: *** [Makefile:202: fastfetch] Error 2
> ```

pkg install vulkan-headers

**Comment by Dan1jel** [comment]
> > > > #1  0x00000055556293c8 in ?? ()
> > > #2  0x000000555562916c in ?? ()
> > > #3  0x0000005555605f94 in ?? ()
> > > #4  0x00000055555ccab8 in ?? ()
> > > #5  0x00000055556579d8 in ?? ()
> > > 
> > > It seems that the binary compiled by termux doesn't include debug symbols. Can you please compile it from source and try again?
> > > 
> > > Or you may use this one: [fastfetch.gz](https://github.com/fastfetch-cli/fastfetch/files/14086212/fastfetch.gz)
> > 
> > When I try to compile using 
> > ```
> > run.sh
> > ```
> > I get this error message 
> > ```
> > [ 18%] Building C object CMakeFiles/libfastfetch.dir/src/detection/terminaltheme/terminaltheme.c.o
> > [ 18%] Building C object CMakeFiles/libfastfetch.dir/src/detection/terminalfont/terminalfont.c.o
> > [ 19%] Building C object CMakeFiles/libfastfetch.dir/src/detection/terminalshell/terminalshell.c.o
> > [ 20%] Building C object CMakeFiles/libfastfetch.dir/src/detection/version/version.c.o
> > [ 20%] Building C object CMakeFiles/libfastfetch.dir/src/detection/vulkan/vulkan.c.o
> > [ 21%] Building C object CMakeFiles/libfastfetch.dir/src/detection/weather/weather.c.o
> > [ 21%] Building C object CMakeFiles/libfastfetch.dir/src/logo/builtin.c.o
> > /data/data/com.termux/files/home/fastfetch/src/detection/vulkan/vulkan.c:12:10: fatal error: 'vulkan/vulkan.h' file not found
> >    12 | #include <vulkan/vulkan.h>
> >       |          ^~~~~~~~~~~~~~~~~
> > 1 error generated.
> > make[3]: *** [CMakeFiles/libfastfetch.dir/build.make:524: CMakeFiles/libfastfetch.dir/src/detection/vulkan/vulkan.c.o] Error 1
> > make[3]: *** Waiting for unfinished jobs....
> > make[2]: *** [CMakeFiles/Makefile2:87: CMakeFiles/libfastfetch.dir/all] Error 2
> > make[1]: *** [CMakeFiles/Makefile2:120: CMakeFiles/fastfetch.dir/rule] Error 2
> > make: *** [Makefile:202: fastfetch] Error 2
> > ```
> 
> pkg install vulkan-headers

Still get same result. "Segmentation Fault".

**Comment by CarterLi** [comment]
gdb please

**Comment by Dan1jel** [comment]
> gdb please

```
gdb fastfetch/build/fastfetch
GNU gdb (GDB) 14.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.htm>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-android".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from fastfetch/build/fastfetch...
(No debugging symbols found in fastfetch/build/fastfetch)
(gdb) run
Starting program: /data/data/com.termux/files/home/fastfetch/build/fastfetc
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/data/data/com.termux/files/usr/lib/libthr.
warning: section .note.gnu.build-id not found in .gnu_debugdata for /apex/co
warning: section .dynsym not found in .gnu_debugdata for /apex/com.android.o
warning: section .gnu.version not found in .gnu_debugdata for /apex/com.ando
warning: section .gnu.version_d not found in .gnu_debugdata for /apex/com.ao
warning: section .gnu.hash not found in .gnu_debugdata for /apex/com.androio
warning: section .got.plt not found in .gnu_debugdata for /apex/com.androido
warning: section .bss not found in .gnu_debugdata for /apex/com.android.vndo
                                      Mali-G715 [Integrated]
                                      8.40 GiB / 11.32 GiB (74%)
                                      237 (dpkg)
[Detaching after fork from child process 32061]
                                      fish 3.7.0
[Detaching after fork from child process 32062]

Program received signal SIGSEGV, Segmentation fault.
0x0000007ff6284d30 in long long StrToI<long long, -9223372036854775808ll, 9)
   from /apex/com.android.runtime/lib64/bionic/libc.so
(gdb)
```

**Comment by CarterLi** [comment]
bt

**Comment by Dan1jel** [comment]
> bt

```
(gdb) bt
#0  0x0000007ff6284d30 in long long StrToI<long long, -9223372036854775808l)
   from /apex/com.android.runtime/lib64/bionic/libc.so
#1  0x00000055556283b4 in getTerminalInfoByPidEnv ()
#2  0x0000005555628188 in ffDetectTerminal ()
#3  0x0000005555605aa0 in ffPrintTerminal ()
#4  0x00000055555ce1a8 in ffPrintJsonConfig ()
#5  0x00000055555c75a8 in main ()
(gdb)
```

**Comment by CarterLi** [comment]
Should be fixed in aaa091f23b5d3d97082133eacdabbe2a5b61cd6e. Please pull the latest code and try again

**Comment by Dan1jel** [comment]
> Should be fixed in aaa091f23b5d3d97082133eacdabbe2a5b61cd6e. Please pull the latest code and try again

Yes, after I rebuild from source, and I run fastfetch form build folder it works again 👌
