### ISSUE TITLE
[BUG] Running 'fastfetch --help disk-format' on archlinux creates a segfault

### ISSUE THREAD

**Issue by qweri0p** [fastfetch-cli/fastfetch#749]
# Running fastfetch with `--help disk-format` it prints part of the output, then segfault.

* What happened: Segfault
* What should happen: No segfault
* Did it work in an older version: I don't know
* Where did you get the binary: Installed with pacman from official archlinux repos
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Yes it does.

# Often helpful information:

Screenshot:
```
$ fastfetch --help disk-format       
--disk-format:
Sets the format string for Disk output.
To see how a format string is constructed, take a look at "fastfetch --help format".
The following values are passed:
        {1}: Size used
        {2}: Size total
        {3}: Size percentage
        {4}: Files used
        {5}: Files total
        {6}: Files percentage
        {7}: True if external volume
        {8}: True if hidden volume
        {9}: Filesystem
zsh: segmentation fault (core dumped)  fastfetch --help disk-format
```

Output of `fastfetch -c ci.jsonc --format json`:

```
[
  {
    "type": "Title",
    "result": {
      "userName": "qweriop",
      "hostName": "compUwUter10000",
      "homeDir": "/home/qweriop/",
      "exePath": "/usr/bin/fastfetch",
      "userShell": "/bin/zsh",
      "pageSize": 4096
    },
    "stat": 0
  },
  {
    "type": "OS",
    "result": {
      "buildID": "rolling",
      "codename": "",
      "id": "arch",
      "idLike": "",
      "name": "Arch Linux",
      "prettyName": "Arch Linux",
      "variant": "",
      "variantID": "",
      "version": "",
      "versionID": ""
    },
    "stat": 0
  },
  {
    "type": "Kernel",
    "result": {
      "architecture": "x86_64",
      "name": "Linux",
      "release": "6.7.8-arch1-1",
      "version": "#1 SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 00:30:36 +0000",
      "displayVersion": ""
    },
    "stat": 0
  },
 
  {
    "type": "Memory",
    "result": {
      "total": 8165335040,
      "used": 4926177280
    },
    "stat": 0
  },
  {
    "type": "Swap",
    "result": {
      "total": 8589930496,
      "used": 406847488
    },
    "stat": 0
  },
  {
    "type": "Disk",
    "result": [
      {
        "bytes": {
          "available": 11670851584,
          "free": 17056337920,
          "total": 105089261568,
          "used": 88032923648
        },
        "files": {
          "total": 6553600,
          "used": 691604
        },
        "filesystem": "ext4",
        "mountpoint": "/",
        "mountFrom": "/dev/nvme0n1p3",
        "name": "ARCHROOT",
        "volumeType": [
          "Regular"
        ]
      },
      {
        "bytes": {
          "available": 169021440,
          "free": 169021440,
          "total": 313942016,
          "used": 144920576
        },
        "files": {
          "total": 0,
          "used": 0
        },
        "filesystem": "vfat",
        "mountpoint": "/boot",
        "mountFrom": "/dev/nvme0n1p1",
        "name": "ARCHBOOT",
        "volumeType": [
          "Hidden"
        ]
      },
      {
        "bytes": {
          "available": 12234125312,
          "free": 22988320768,
          "total": 210241560576,
          "used": 187253239808
        },
        "files": {
          "total": 13107200,
          "used": 1324941
        },
        "filesystem": "ext4",
        "mountpoint": "/home",
        "mountFrom": "/dev/nvme0n1p2",
        "name": "home",
        "volumeType": [
          "Regular"
        ]
      }
    ],
    "stat": 0
  },
  {
    "type": "DiskIO",
    "result": [
      {
        "name": "Samsung SSD 970 EVO 500GB",
        "devPath": "/dev/nvme0n1",
        "bytesRead": 79679488,
        "bytesWritten": 57344,
        "readCount": 864,
        "writeCount": 6
      }
    ],
    "stat": 0
  },
  {
    "type": "PhysicalDisk",
    "result": [
      {
        "name": "Samsung SSD 970 EVO 500GB",
        "devPath": "/dev/nvme0n1",
        "interconnect": "NVMe",
        "kind": "SSD",
        "size": 500107862016,
        "serial": "S466NX0M855078F",
        "removable": false,
        "readOnly": false,
        "revision": "2B2QEXE7",
        "temperature": null
      }
    ],
    "stat": 0
  },
  {
    "type": "Version",
    "result": {
      "projectName": "fastfetch",
      "architecture": "x86_64",
      "version": "2.8.7",
      "versionTweak": "",
      "cmakeBuiltType": "RelWithDebInfo",
      "compileTime": "Mar  2 2024, 16:12:34",
      "compiler": "gcc 13.2.1",
      "debugMode": false,
      "libc": "glibc 2.39"
    },
    "stat": 0
  }
]%
```

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
videodev2
Directx Headers
Proprietary GPU driver API
```

## Stacktrace

```
Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
76		VPCMPEQ	(%rdi), %ymm0, %ymm1                                                          
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
No locals.
#1  0x00007ffff7d00b09 in __printf_buffer (buf=buf@entry=0x7fffffffda80, 
    format=format@entry=0x5555556078b8 "        {%u}: %s\n", ap=ap@entry=0x7fffffffdb80, 
    mode_flags=mode_flags@entry=2)
    at /usr/src/debug/glibc/glibc/stdio-common/vfprintf-process-arg.c:435
        len = <optimized out>
        iter = {remaining_in_current_group = 19016, remaining = 0, 
          groupings = 0xcef0 <error: Cannot access memory at address 0xcef0>, 
          non_repeating_groups = 4096, separators = 0}
        octal_marker = <optimized out>
        ptrptr = 0xffffffff
        written = <optimized out>
        number_slow_path = <optimized out>
        number_length = <optimized out>
        prec_inc = <optimized out>
        signed_number = <optimized out>
        step0_jumps = {0, 1435, 1331, 3611, 3507, 1843, 1731, 2707, 3827, 1499, 3723, 2499, 2387, 
          2283, 4131, 4083, 3395, 2875, 3971, 323, 1075, 931, 3995, 1619, 1219, 699, 327, 2179, 
          2075, 4171, 3947, 1955}
        space = <optimized out>
        is_short = <optimized out>
        use_outdigits = <optimized out>
        step1_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 1499, 3723, 2499, 2387, 2283, 4131, 4083, 3395, 
          2875, 3971, 323, 1075, 931, 3995, 1619, 1219, 699, 327, 2179, 2075, 0, 3947, 1955}
        group = <optimized out>
        prec = <optimized out>
        is_fast = <optimized out>
        step2_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3723, 2499, 2387, 2283, 4131, 4083, 3395, 2875, 
--Type <RET> for more, q to quit, c to continue without paging--
          3971, 323, 1075, 931, 3995, 1619, 1219, 699, 327, 2179, 2075, 0, 3947, 1955}
        string = <optimized out>
        left = 0
        is_long_double = <optimized out>
        width = <optimized out>
        bitwidth = <optimized out>
        step3a_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2603, 0, 0, 0, 4131, 4083, 3395, 2875, 3971, 
          0, 0, 0, 0, 1619, 0, 0, 0, 0, 0, 0, 3947, 0}
        alt = <optimized out>
        showsign = <optimized out>
        is_long = <optimized out>
        is_char = <optimized out>
        pad = 32 ' '
        step3b_jumps = {0 <repeats 11 times>, 2387, 0, 0, 4131, 4083, 3395, 2875, 3971, 323, 1075, 
          931, 3995, 1619, 1219, 699, 327, 0, 0, 0, 3947, 0}
        step4_jumps = {0 <repeats 14 times>, 4131, 4083, 3395, 2875, 3971, 323, 1075, 931, 3995, 
          1619, 1219, 699, 327, 0, 0, 0, 3947, 0}
        is_negative = <optimized out>
        number = <optimized out>
        base = <optimized out>
        the_arg = {pa_wchar = 1920128 L'\x1d4c80', pa_int = 1920128, pa_long_int = 1920128, 
          pa_long_long_int = 1920128, pa_u_int = 1920128, pa_u_long_int = 1920128, 
          pa_u_long_long_int = 1920128, pa_double = 9.4866928041786104e-318, 
          pa_long_double = <invalid float value>, 
          pa_float128 = 2.29351413735569234132437995169912305e-4940, 
          pa_string = 0x1d4c80 <error: Cannot access memory at address 0x1d4c80>, 
          pa_wstring = 0x1d4c80 <error: Cannot access memory at address 0x1d4c80>, 
          pa_pointer = 0x1d4c80, pa_user = 0x1d4c80}
        spec = <optimized out>
        thousands_sep = <optimized out>
        grouping = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>
        f = 0x5555556078c7 "s\n"
        lead_str_end = 0x5555556078c1 "%u}: %s\n"
        end_of_spec = <optimized out>
        work_buffer = "\004\000\000\000\004\000\000\000P\003\000\000\000\000\000\000P\003\000\000\000\000\000\000P\003\000\000\000\000\000\000P\000\000\000\000\000\000\000P\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000\004\000\000\000\004\000\000\000\240\003\000\000\000\000\000\000\240\003\000\000\000\000\000\000\240\003\000\000\000\000\000\000D\000\000\000\000\000\000\000D\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\a\000\000\000\004\000\000\000\200<\035\000\000\000\000\000\200L\035\000\000\000\000\000\200L\035\000\000\000\000\000\020\000\000\000\000\000\000\000\210\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000S\345td\004\000\000\000P\003\000\000\000\000\000\000P\003\000\000\000\000\000\000P\003\000\000\000\000\000\000"...
        workend = 0x7fffffffda08 ""
        ap_save = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdc60, 
            reg_save_area = 0x7fffffffdba0}}
        nspecs_done = 1
        save_errno = 2
        readonly_format = 0
        do_longlong_number = <optimized out>
#2  0x00007ffff7d01272 in __vfprintf_internal (s=0x7ffff7e7b5c0 <_IO_2_1_stdout_>, 
--Type <RET> for more, q to quit, c to continue without paging--
    format=0x5555556078b8 "        {%u}: %s\n", ap=ap@entry=0x7fffffffdb80, 
    mode_flags=mode_flags@entry=2) at vfprintf-internal.c:1544
        wrap = {base = {
            write_base = 0x7fffffffdab0 "        {10}: ilesystem\nden volume\ne\nt.\n\277\360\334\367\377\177", write_ptr = 0x7fffffffdabe "ilesystem\nden volume\ne\nt.\n\277\360\334\367\377\177", 
            write_end = 0x7fffffffdb30 "", written = 0, mode = __printf_buffer_mode_to_file}, 
          fp = 0x7ffff7e7b5c0 <_IO_2_1_stdout_>, 
          stage = "        {10}: ilesystem\nden volume\ne\nt.\n\277\360\334\367\377\177\000\000\001\000\000\000\000\000\000\000\300\252\347\367\377\177\000\000\377\000\000\000\000\000\000\000\300\377\377\377\377\377\377\377\000\004\000\000\000\000\000\000\001\000\000\000\000\000\000\000\350\003\000\000\000\000\000\000\352\330\323\367\377\177\000\000P\220\347\367\377\177\000\000\260xhUUU\000"}
        done = <optimized out>
        __result = <optimized out>
#3  0x00007ffff7db755b in ___printf_chk (flag=flag@entry=1, 
    format=format@entry=0x5555556078b8 "        {%u}: %s\n") at printf_chk.c:33
        mode = 2
        ap = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffdc60, 
            reg_save_area = 0x7fffffffdba0}}
        ret = <optimized out>
#4  0x00005555555689f7 in printf (__fmt=<optimized out>, __fmt=<optimized out>)
    at /usr/include/bits/stdio2.h:86
No locals.
#5  ffPrintModuleFormatHelp (name=<optimized out>, def=0x555555609235 "{1} / {2} ({3}) - {9}", 
    numArgs=<optimized out>, args=0x7fffffffdcc0)
    at /usr/src/debug/fastfetch/fastfetch-2.8.7/src/common/printing.c:146
        i = 9
        buffer = {allocated = 32, length = 4, chars = 0x555555688230 "disk"}
#6  0x0000555555588630 in ffPrintDiskHelpFormat ()
    at /usr/src/debug/fastfetch/fastfetch-2.8.7/src/modules/disk/disk.c:456
No locals.
#7  0x000055555555fd9b in printCommandFormatHelp (command=<optimized out>)
    at /usr/src/debug/fastfetch/fastfetch-2.8.7/src/fastfetch.c:32
        baseInfo = 0x555555683e20 <instance+2464>
        modules = 0x555555683258 <D.lto_priv.0+24>
        type = {allocated = 32, length = 4, chars = 0x555555688200 "disk"}
        type = <optimized out>
        modules = <optimized out>
        __res = <optimized out>
        __c = <optimized out>
        baseInfo = <optimized out>
#8  printCommandHelp (command=<optimized out>)
    at /usr/src/debug/fastfetch/fastfetch-2.8.7/src/fastfetch.c:258
No locals.
#9  parseCommand (data=<optimized out>, key=<optimized out>, value=<optimized out>)
    at /usr/src/debug/fastfetch/fastfetch-2.8.7/src/fastfetch.c:564
        subkey = <optimized out>
        subkey = <optimized out>
#10 0x000055555555dfb6 in parseArguments (data=data@entry=0x7fffffffdf20, argc=argc@entry=3, 
    argv=argv@entry=0x7fffffffe258, parser=parser@entry=0x55555555fc20 <parseCommand>)
    at /usr/src/debug/fastfetch/fastfetch-2.8.7/src/fastfetch.c:779
--Type <RET> for more, q to quit, c to continue without paging--
        key = 0x7fffffffe62e "--help"
        i = 1
#11 0x000055555555c41f in main (argc=3, argv=0x7fffffffe258)
    at /usr/src/debug/fastfetch/fastfetch-2.8.7/src/fastfetch.c:879
        data = {structure = {allocated = 0, length = 0, chars = 0x555555608657 ""}, customValues = {
            data = 0x0, elementSize = 40, length = 0, capacity = 0}, configLoaded = false}
```

Issue only occurs on arch.

Tested on a Raspberry Pi (aarch64) (raspbian) (built from source), no issue.
Tested on openSUSE Leap 15.5 (x86_64) (both binary package and build from source), no issue.
Tested it on both arch devices I own as well as a clean VM, segfault.
Both the package in the 'extra' repo as well as building from source create the segfault
Issue also occurs when using the nix package on arch with `nix-shell -p fastfetch`. (nix channel is nixpkgs-unstable)

**Comment by CarterLi** [comment]
Thanks for testing.
