### ISSUE TITLE
[BUG] segfault at ffPrintBattery on termux

### ISSUE THREAD

**Issue by dm9pZCAq** [fastfetch-cli/fastfetch#838]
# General description of bug:

on termux when running just `fastfetch` without any config it segfaults, I figured out this is due to battery component
so minimal reproducible example is `fastfetch -s Battery`, but when running without logo segfault not happens for me (`fastfetch -l none -s Battery`)

* Fastfetch version used: 2.11.0 (aarch64)
* Where did you get the binary: `pkg i fastfetch` (termux repo)

maybe this is also related to: #760

# Often helpful information:

I compiled it from source (dev 9afcc002) to debug with gdb:
```sh
cmake .. -DENABLE_VULKAN=no
cmake --build . --target fastfetch
```
then run it in gdb:
```gdb
(gdb) set args -s Battery
(gdb) run
...
(gdb) bt
#0  0x0000007fbdd98648 in scudo::Allocator<scudo::AndroidConfig, &scudo_malloc_postinit>::deallocate(void*, scudo::Chunk::Origin, unsigned long, unsigned long) () from /apex/com.android.runtime/lib64/bionic/libc.so
#1  0x00000055555d84d4 in ffStrbufDestroy (strbuf=0x7e6dc49060) at /data/data/com.termux/files/home/test/fastfetch/src/util/FFstrbuf.h:175
#2  ffPrintBattery (options=0x555566b5e8 <instance+512>) at /data/data/com.termux/files/home/test/fastfetch/src/modules/battery/battery.c:99
#3  0x00000055555cc088 in ffPrintCommandOption (data=data@entry=0x7fffffef70, jsonDoc=0x0) at /data/data/com.termux/files/home/test/fastfetch/src/common/commandoption.c:137
#4  0x00000055555c8710 in run (data=0x7fffffef70) at /data/data/com.termux/files/home/test/fastfetch/src/fastfetch.c:819
#5  main (argc=3, argv=0x7ffffff068) at /data/data/com.termux/files/home/test/fastfetch/src/fastfetch.c:880
(gdb) frame 2
#2  ffPrintBattery (options=0x555566b5e8 <instance+512>) at /data/data/com.termux/files/home/test/fastfetch/src/modules/battery/battery.c:99
99                  ffStrbufDestroy(&result->serial);
(gdb) list
94
95                  ffStrbufDestroy(&result->manufacturer);
96                  ffStrbufDestroy(&result->modelName);
97                  ffStrbufDestroy(&result->technology);
98                  ffStrbufDestroy(&result->status);
99                  ffStrbufDestroy(&result->serial);
100                 ffStrbufDestroy(&result->manufactureDate);
101             }
102             if(results.length == 0)
103                 ffPrintError(FF_BATTERY_MODULE_NAME, 0, &options->moduleArgs, FF_PRINT_TYPE_DEFAULT, "No batteries found");
```
so segfault happens at `ffStrbufDestroy(&result->serial);`

also I put breakpoint at `ffPrintBattery` and checked result before all of this `ffStrbufDestroy`:
```gdb
(gdb) p *result
$27 = {manufacturer = {allocated = 0, length = 0, chars = 0x5555580d99 ""}, manufactureDate = {allocated = 0, length = 0, chars = 0x5555580d99 ""}, modelName = {allocated = 0, length = 0, chars = 0x5555580d99 ""}, technology = {
    allocated = 0, length = 0, chars = 0x5555580d99 ""}, status = {allocated = 32, length = 11, chars = 0x7d6dc4e2b0 "DISCHARGING"}, serial = {allocated = 1296911693, length = 728583501,
    chars = 0x2020200a20202020 <error: Cannot access memory at address 0x2020200a20202020>}, capacity = 40, temperature = nan(0x8000000000000), cycleCount = 0}
```
and `result->serial` looks corrupted

**Comment by CarterLi** [comment]
Okey. This explained #760

**Comment by CarterLi** [comment]
Thanks for testing. It was very helpful!
