### ISSUE TITLE
Segmentation fault on Debian 11

### ISSUE THREAD

**Issue by CaKrome** [fastfetch-cli/fastfetch#845]
# General description of bug:

* What happened: Seg fault when running fastfetch
* What should happen: no errror
* Fastfetch version used: 2.11.1 
* Did it work in an older version: no  
* Where did you get the binary:  Github Release

## If fastfatch crashed or freezed

```shell
xxxxx@xxxxx:~$ gdb -q -ex 'set confirm off' -ex run -ex 'bt full' -ex quit --args fastfetch
Reading symbols from fastfetch...
Starting program: /usr/bin/fastfetch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
       _,met$$$$$gg.           xxxxx@xxxxx
    ,g$$$$$$$$$$$$$$$P.        --------------------
  ,g$$P"         """Y$$.".     OS: Debian GNU/Linux bullseye 11.9 x86_64
 ,$$P'               `$$$.     Host: B550M Pro4
',$$P       ,ggs.     `$$b:    Kernel: 5.10.0-27-amd64
`d$$'     ,$P"'   .    $$$     Uptime: 108 days(!), 1 hour
 $$P      d$'     ,    $$$P    Packages: 814 (dpkg)
[Detaching after fork from child process 3485713]
 $$;      Y$b._   _,d$P'       Shell: bash 5.1.4
 Y$$.    `.`"Y$$$$P"'          Cursor: Adwaita
 `$$b      "-.__               Terminal: /dev/pts/0
  `Y$$                         CPU: AMD Ryzen 5 5600G (12) @ 5.00 GHz
   `Y$$.    
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7eaefb0 in __lll_cas_lock (futex=0x4) at ../sysdeps/unix/sysv/linux/x86/lowlevellock.h:47
47      ../sysdeps/unix/sysv/linux/x86/lowlevellock.h: No such file or directory.
#0  0x00007ffff7eaefb0 in __lll_cas_lock (futex=0x4) at ../sysdeps/unix/sysv/linux/x86/lowlevellock.h:47
        ret = <optimized out>
#1  __GI___readdir64 (dirp=dirp@entry=0x0) at ../sysdeps/posix/readdir.c:44
        dp = <optimized out>
        saved_errno = 2
#2  0x00005555555a3031 in pciDetectAmdSpecific (options=<optimized out>, options=<optimized out>, 
    buffer=0x7fffffffdeb0, pciDir=0x7fffffffdea0, gpu=0x55555569a910)
    at /home/runner/work/fastfetch/fastfetch/src/detection/gpu/gpu_linux.c:50
        hwmonLen = <optimized out>
        value = <optimized out>
        pciDirLen = 33
        dirp = 0x0
        entry = <optimized out>
        pciDirLen = <optimized out>
        dirp = <optimized out>
        entry = <optimized out>
        hwmonLen = <optimized out>
        value = <optimized out>
#3  detectPci (options=0x555555681fb0 <instance+3024>, gpus=<optimized out>, buffer=0x7fffffffdeb0, 
    drmDir=0x7fffffffdea0) at /home/runner/work/fastfetch/fastfetch/src/detection/gpu/gpu_linux.c:212
        drmDirPathLength = 33
        vendorId = 4098
        deviceId = 5688
        subVendorId = 4098
        subDeviceId = 5686
        classId = 3 '\003'
        subclassId = 0 '\000'
        pciPath = "../../../devices/pci0000:00/0000:00:08.1/0000:05:00.0\000 1359 18446744073709551615 945608-
6654720 94560827419805 140731056775776 0\000\002\000\000\000\000\000\000h7hUUU\000\000\000\000\000\000\000\00.
        pathLength = <optimized out>
        pPciPath = <optimized out>
        pciDomain = 0
        pciBus = 5
        pciDevice = 0
        pciFunc = 0
        gpu = 0x55555569a910
        pciids = {allocated = 1254399, length = 1254398, 
          chars = 0x7ffff7850010 "#\n#\tList of PCI ID's\n#\n#\tVersion: 2021.02.08\n#\tDate:    2021-02-08 0}
#4  0x0000555555583f59 in pciDetectGPUs (gpus=0x7fffffffdf90, options=0x555555681fb0 <instance+3024>)
    at /home/runner/work/fastfetch/fastfetch/src/detection/gpu/gpu_linux.c:350
        pciDevDirLength = 33
        pciDirPath = 0x55555560e5cf "/sys/bus/pci/devices/"
        pciBaseDirLength = 21
        buffer = {allocated = 4097, length = 5, chars = 0x555555699900 "0xc9\n"}
        dirp = 0x5555556918c0
        pciDir = {allocated = 64, length = 40, 
          chars = 0x5555556894b0 "/sys/bus/pci/devices/0000:05:00.0/hwmon/"}
        entry = <optimized out>
        pciDirPath = <optimized out>
        dirp = <optimized out>
        pciDir = {allocated = <optimized out>, length = <optimized out>, chars = <optimized out>}
        pciBaseDirLength = <optimized out>
        buffer = {allocated = <optimized out>, length = <optimized out>, chars = <optimized out>}
        entry = <optimized out>
        pciDevDirLength = <optimized out>
#5  ffDetectGPUImpl (gpus=0x7fffffffdf90, options=0x555555681fb0 <instance+3024>)
    at /home/runner/work/fastfetch/fastfetch/src/detection/gpu/gpu_linux.c:368
No locals.
#6  ffDetectGPU.constprop.0 (options=options@entry=0x555555681fb0 <instance+3024>, 
--Type <RET> for more, q to quit, c to continue without paging--
    result=result@entry=0x7fffffffdf90) at /home/runner/work/fastfetch/fastfetch/src/detection/gpu/gpu.c:106
        error = <optimized out>
        vulkan = <optimized out>
#7  0x00005555555dfe2f in ffPrintGPU (options=0x555555681fb0 <instance+3024>)
    at /home/runner/work/fastfetch/fastfetch/src/modules/gpu/gpu.c:98
        gpus = {data = 0x55555569a910 "", elementSize = 136, length = 1, capacity = 16}
        error = <optimized out>
        selectedGPUs = {data = 0x7fffffffdfa0 "\020", elementSize = 4294959024, length = 32767, 
          capacity = 1432885456}
#8  0x0000555555602be8 in parseStructureCommand (line=0x55555568677d "GPU", 
    fn=fn@entry=0x5555556015d0 <genJsonResult>, jsonDoc=jsonDoc@entry=0x0, customValues=<optimized out>, 
    customValues=<optimized out>) at /home/runner/work/fastfetch/fastfetch/src/common/commandoption.c:115
        baseInfo = 0x555555681fb0 <instance+3024>
        modules = 0x5555556812b8 <G.lto_priv.0+8>
#9  0x000055555556b27d in ffPrintCommandOption (jsonDoc=<optimized out>, data=0x7fffffffe1c0)
    at /home/runner/work/fastfetch/fastfetch/src/common/commandoption.c:137
        colonIndex = 128
        ms = 0
        startIndex = 125
        startIndex = <optimized out>
        colonIndex = <optimized out>
        ms = <optimized out>
        moduleJson = <optimized out>
        str = {<optimized out> <repeats 32 times>}
        len = <optimized out>
#10 run (data=0x7fffffffe1c0) at /home/runner/work/fastfetch/fastfetch/src/fastfetch.c:819
        useJsonConfig = <optimized out>
        useJsonConfig = <optimized out>
#11 main (argc=<optimized out>, argv=<optimized out>)
    at /home/runner/work/fastfetch/fastfetch/src/fastfetch.c:880
        data = {structure = {allocated = 256, length = 194, chars = 0x555555686700 "Title"}, customValues = {
            data = 0x0, elementSize = 40, length = 0, capacity = 0}, configLoaded = false}
```

**Comment by CarterLi** [comment]
I forgot check NULL returned by opendir once again...
